version: "3.7"

services:
  # backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    networks:
      - stack

  # frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - backend
    networks:
      - stack

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - stack

  # mysql
  mysql:
    image: mysql:8.0.31
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: qyos_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - stack

networks:
  stack:
    driver: bridge
