version: "3.7"

services:
    # image project
    api-backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api-backend
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        networks:
            - backend

    # nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./nginx/:/etc/nginx/conf.d/
        networks:
            - backend

    # db mysql
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ../mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - backend

networks:
    backend:
        driver: bridge
